### ISSUE TITLE
Latest version on CF channel is 0.9.6

### ISSUE THREAD

**Issue by npavlovikj** [conda-forge/monty-feedstock#11]
Hi,

Although the version in the recipe is `2.0.4`, the one available in the CF channel is `0.9.6`:
```
$ conda search monty
Loading channels: done
# Name                       Version           Build  Channel
monty                          0.9.6          py27_0  conda-forge/label/cf201901
monty                          0.9.6          py27_0  conda-forge
monty                          0.9.6          py34_0  conda-forge/label/cf201901
monty                          0.9.6          py34_0  conda-forge
monty                          0.9.6          py35_0  conda-forge/label/cf201901
monty                          0.9.6          py35_0  conda-forge
monty                          0.9.6          py36_0  conda-forge/label/cf201901
monty                          0.9.6          py36_0  conda-forge
```

Is there a reason why the newest version is not being shown in the channel?

Thank you,
Natasha

**Comment by npavlovikj** [comment]
Ah, looks like the last merge request failed. I don't have permissions to re-run the workflow, so @shyuep can you please do that ?

**Comment by shyuep** [comment]
Hi there, I am not sure how to rerun the workflow. I checked the meta.yaml and it does seem correct and there shouldn't be any issues. So I am not sure how this occured.
